name 'brucem-ezpublish'
version '0.1.1'
source 'git://github.com/brucem/puppet-ezpublish.git'
author 'Bruce Morrison'
license 'Apache 2.0'
summary 'eZ Publish Module'
description 'eZ Publish Module'
project_page 'http://github.com/brucem/puppet-ezpublish'
dependency 'puppetlabs/mysql',  '1.0.0'
dependency 'puppetlabs/apache', '0.9.0'
dependency 'example42/php', '2.0.11'
