name 'brucem-ezpublish'
version '0.0.6'
source 'git://github.com/brucem/puppet-ezpublish.git'
author 'Bruce Morrison'
license 'Apache 2.0'
summary 'eZ Publish Module'
description 'eZ Publish Module'
project_page 'http://github.com/brucem/puppet-ezpublish'
dependency 'puppetlabs/mysql',  '>=0.6.1'
dependency 'puppetlabs/apache', '>=0.6.0'
dependency 'example42/php', '>=2.0.8'
